# -*- coding: utf-8 -*-
"""Fake_news_detection_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVuE6k_ZVDbvBdTpZdtRIyd9AJRoXf72
"""

import numpy as np
import pandas as pd
import re
import nltk
import matplotlib.pyplot as plt

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Dropout, Bidirectional

nltk.download('stopwords')

import kagglehub

# Download latest version
path = kagglehub.dataset_download("clmentbisaillon/fake-and-real-news-dataset")

print("Path to dataset files:", path)

df_fake = pd.read_csv(path + "/Fake.csv")
df_fake.head()

df_fake.shape

df_real = pd.read_csv(path + "/True.csv")
df_real.head()

df_real.shape

# Labeling Data for classification
df_fake['label'] = 0
df_real['label'] = 1

# Merging both Datasets
data = pd.concat([df_fake, df_real])

# Shuffling the combined data for better model
data = data.sample(frac=1).reset_index(drop=True)

data.head()

data.shape

data['label'].value_counts()

data.columns

# Remove unnecessary columns
data = data.drop(['subject', 'date'], axis=1)

# Combine Title + Text
data['content'] = data['title'] + " " + data['text']

data.head()

data = data.dropna()

# Now creating Text Cleaning Function using NLP

stop_words = set(stopwords.words('english'))

def clean_text(text):
  text = text.lower()       # Converts text to lowercase
  text = re.sub(r'http\S+', '', text)   # Removes URLs
  text = re.sub(r'[^a-zA-Z]', ' ', text)   # Removes punctuation/numbers
  words = text.split()
  words = [word for word in words
           if word not in stop_words]   # Removes unnecessary words
  return " ".join(words)

# Apply Cleaning
data['content'] = data['content'].apply(clean_text)

data = data.drop_duplicates(subset=['content'])

data['content'][0]

# Creating Features
X = data['content']
y = data['label']

# Train Test Split
X_train_text, X_test_text, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Tokenization
tokenizer = Tokenizer(num_words=10000, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train_text)

X_train_seq = tokenizer.texts_to_sequences(X_train_text)
X_test_seq = tokenizer.texts_to_sequences(X_test_text)

# Padding for same length
X_train = pad_sequences(X_train_seq, maxlen=300)
X_test = pad_sequences(X_test_seq, maxlen=300)

print(X_train.shape)
print(X_test.shape)

"""LSTM Model"""

#LSTM model
model = Sequential()

model.add(Embedding(input_dim=10001, output_dim=128))
model.add(LSTM(64, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Early Stopping
from tensorflow.keras.callbacks import EarlyStopping
early_stop = EarlyStopping(monitor='val_loss',patience=2,restore_best_weights=True)

model.summary()

# Train LSTM model
history = model.fit(X_train, y_train, batch_size=64, epochs=5,
                    validation_split=0.2, callbacks=[early_stop])

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

predictions = model.predict(X_test)

print(predictions)

# Convert Probabilities to Labels
predicted_labels = (predictions > 0.5).astype("int32").flatten()

print(classification_report(y_test, predicted_labels))

cm = confusion_matrix(y_test, predicted_labels)
print(cm)

"""Let's test it"""

def predict_news(news):

    news = clean_text(news)

    seq = tokenizer.texts_to_sequences([news])

    padded = pad_sequences(seq, maxlen=500)

    pred = model.predict(padded, verbose=0)[0][0]

    confidence = pred if pred > 0.5 else 1 - pred

    print(f"Raw Prediction Score: {pred:.4f}")

    if pred > 0.5:
        print(f"🟢 REAL NEWS ({confidence*100:.2f}% confidence)")
    else:
        print(f"🔴 FAKE NEWS ({confidence*100:.2f}% confidence)")

real_news = """
NASA announced the successful launch of a new climate monitoring satellite designed to study global warming and atmospheric changes.
"""

predict_news(real_news)

fake_news = """
India defeated Australia by 5 wickets in the final ODI match after Virat Kohli scored a brilliant century.
"""

predict_news(fake_news)

print(data['label'].value_counts())

